### ISSUE TITLE
Twitch clips being shown without embeds

### ISSUE THREAD

**Issue by fartbagxp** [Renari/Shubot#142]
## Problem statement

The Twitch posting function of the bot runs at a 10 minute interval, right on the dot and posts any recent clips that wasn't in its own nedb database. Discord seems to be having problems with embedding recently clipped Twitch clips, and not showing the entire embed as a video. I recommend delaying the Twitch posting functionality, especially if the clip was recently created (within the last 10 minutes). 
![image](https://user-images.githubusercontent.com/8839850/126754780-9ce68056-0359-4ac3-b413-1a491452ba8b.png)

## Solution

The easiest solution would probably be to modify the GetTwitchClip function https://github.com/Renari/Shubot/blob/master/src/notification-handlers/twitch-notification.ts#L25, to reject clips if they were made within the last x minutes (ex. ten minutes).

**Comment by fartbagxp** [comment]
Testing this out a bit further, it won't work. For some reason or another, discord sporadically fails to pull the unfurled URL and probably is their backend or twitch's issue.

The only workaround available is to keep cache busting via query parameters (ex. add ?abc=123) into the link until it properly resolves... but that means we have to have a way to detect that after sending the message.

**Comment by Renari** [comment]
It looks like this isn't happening anymore, seems it was fixed on either Discord or Twitch's end.
